sonar.projectKey=codeartstest_fifa-worldcup-2026
sonar.organization=codeaartstest
sonar.sources=frontend/src
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/migrations/**